baseURL = 'https://ba-amir.github.io'
languageCode = 'en-gb'
title = 'Slightly Embarassing'
theme = "archie"
pagination.pagerSize = 5

[params.meta]
    favicon = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'
